language: php

php: 
  - 8.0

before_script: 
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix: 
  allow_failures:
    - php: 8.0
  fast_finish: true

notifications:
  on_success: never
  on_failure: always