name: "tests"

on:
  push:
  pull_request:

jobs:
  tests:
    name: "Run tests"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version: ["7.4"]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.1"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.9.0"
        with:
          coverage: "none"
          extensions: "intl"
          php-version: "${{ matrix.php-version }}"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: 'echo "::set-output name=directory::$(composer config cache-dir)"'

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v2.1.0
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-"

      - name: "Install dependencies with composer"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Run tests with phpunit/phpunit"
        run: "vendor/bin/phpunit"
